### ISSUE TITLE
Panel "Help" Fields

### ISSUE THREAD

**Issue by AugustMiller** [PSUGraphicDesign/colevity#18]
We should make a pass over the Panel and write some `help` text for various inputs.

Some things to keep in mind:
- Describe what type of information should be included
- Let the user know how and where the text appears in the front-end
- Be concise!

Example:

``` yml
price:
  label: Ticket Price
  type: text
  icon: money
  help: >
    Enter the ticket price, including the dollar sign, if necessary. Use "Free" if the event is open at no cost!
  width: 1/2
```
